name: GitHub Action Docker

on:
  push:
    branches: [ main-docker-android ]
  pull_request:
    branches: [ main-docker-android ]

jobs:
  build:
    runs-on: ubuntu-22.04 # Works also with self hosted runner supporting docker
    container:
      image: docker://fabernovel/android:api-35-ndk-v1.9.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
#      - name: Exec fastlane
#        uses: fabernovel/docker-android
#        with:
#          docker-android-tag: api-35-gcloud-ndk-v1.9.0
#          exec: |
#            bundle install;
#            bundle exec fastlane build_release

      - name: Fastlane
        run: bundle exec fastlane build_release